@extends('layouts.app')
@section('title','Política de Pagos y Disputas — RialBids')
@section('content')
<style>
.policy-hero{background:linear-gradient(135deg,#0f1923 0%,#1a2d3d 60%,#0f1923 100%);color:#fff;padding:72px 0 56px;text-align:center}
.policy-hero h1{font-size:2.4rem;font-weight:700;margin-bottom:12px}
.policy-hero p{color:#a0b4c4;font-size:1.05rem;max-width:580px;margin:0 auto}
.policy-nav{background:#f7f9fb;border-bottom:1px solid #e2e8ed;position:sticky;top:0;z-index:100}
.policy-nav ul{display:flex;list-style:none;margin:0 auto;padding:0;overflow-x:auto;max-width:960px}
.policy-nav ul li a{display:block;padding:14px 20px;font-size:.87rem;font-weight:600;color:#4a6070;text-decoration:none;border-bottom:3px solid transparent;white-space:nowrap}
.policy-nav ul li a:hover{color:#1a73e8;border-bottom-color:#1a73e8}
.policy-body{max-width:820px;margin:0 auto;padding:48px 24px 80px}
.policy-section{margin-bottom:56px}
.policy-section h2{font-size:1.5rem;font-weight:700;color:#0f1923;margin-bottom:8px;padding-bottom:12px;border-bottom:2px solid #e2e8ed}
.policy-section h3{font-size:1.05rem;font-weight:600;color:#1a73e8;margin:28px 0 8px}
.policy-section p{color:#3d4f5c;line-height:1.75;margin-bottom:14px;font-size:.97rem}
.policy-section ul{padding-left:20px;color:#3d4f5c;line-height:1.75;font-size:.97rem}
.policy-section ul li{margin-bottom:8px}
.info-box{background:#eaf3ff;border-left:4px solid #1a73e8;border-radius:0 8px 8px 0;padding:16px 20px;margin:20px 0;color:#1a3a5c;font-size:.94rem;line-height:1.65}
.warning-box{background:#fff8e1;border-left:4px solid #f59e0b;border-radius:0 8px 8px 0;padding:16px 20px;margin:20px 0;color:#5c3d00;font-size:.94rem;line-height:1.65}
.protect-box{background:#f0fdf4;border-left:4px solid #16a34a;border-radius:0 8px 8px 0;padding:16px 20px;margin:20px 0;color:#14532d;font-size:.94rem;line-height:1.65}
.steps-list{counter-reset:steps;list-style:none;padding-left:0}
.steps-list li{counter-increment:steps;display:flex;gap:14px;margin-bottom:16px;align-items:flex-start}
.steps-list li::before{content:counter(steps);background:#1a73e8;color:#fff;font-size:.8rem;font-weight:700;min-width:26px;height:26px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-top:2px;flex-shrink:0}
.policy-table{width:100%;border-collapse:collapse;margin:20px 0;font-size:.93rem}
.policy-table th{background:#0f1923;color:#fff;padding:12px 16px;text-align:left;font-weight:600}
.policy-table td{padding:12px 16px;border-bottom:1px solid #e2e8ed;color:#3d4f5c;vertical-align:top}
.policy-table tr:last-child td{border-bottom:none}
.policy-table tr:nth-child(even) td{background:#f7f9fb}
.contact-cta{background:linear-gradient(135deg,#1a73e8 0%,#0d47a1 100%);color:#fff;border-radius:12px;padding:32px 36px;margin-top:48px;text-align:center}
.contact-cta h3{font-size:1.25rem;margin-bottom:8px;color:#fff}
.contact-cta p{color:#c7dcf8;margin-bottom:20px;font-size:.95rem}
.contact-cta a{background:#fff;color:#1a73e8;font-weight:700;padding:12px 32px;border-radius:8px;text-decoration:none;font-size:.95rem;display:inline-block}
</style>
<div class="policy-hero"><div class="container"><h1>Política de Pagos y Disputas</h1><p>Todo lo que necesitás saber sobre pagos, custodia del dinero y resolución de problemas en RialBids.</p></div></div>
<nav class="policy-nav"><ul><li><a href="#como-funciona">Cómo funciona</a></li><li><a href="#compradores">Compradores</a></li><li><a href="#vendedores">Vendedores</a></li><li><a href="#devoluciones">Devoluciones</a></li><li><a href="#disputas">Disputas</a></li><li><a href="#envios">Envíos</a></li><li><a href="#contacto">Contacto</a></li></ul></nav>
<div class="policy-body">
<div class="policy-section" id="como-funciona"><h2>Cómo funciona RialBids</h2><p>RialBids conecta compradores y vendedores de objetos especiales: joyería, arte, relojes y antigüedades. Actuamos como intermediario neutral: recibimos el pago del comprador, lo retenemos de forma segura en custodia (escrow) y lo liberamos al vendedor una vez confirmada la entrega.</p><p>El contrato de compraventa se celebra siempre entre el comprador y el vendedor. RialBids no es parte de dicho contrato, pero regula su ejecución.</p><div class="info-box"><strong>Pagos seguros:</strong> El 100% del pago queda retenido en custodia vía Stripe hasta 72 horas después de que el tracking confirme la entrega. Si hay un problema, intervenimos antes de liberar el dinero.</div><h3>Flujo general</h3><ol class="steps-list"><li>La subasta finaliza y el comprador paga dentro de 3 días hábiles.</li><li>El 100% del pago queda retenido en custodia vía Stripe — nadie puede disponer de él.</li><li>El vendedor envía con tracking válido dentro de 3 días hábiles.</li><li>El tracking confirma la entrega.</li><li>El comprador tiene 72 horas para revisar y reportar problemas.</li><li>Sin disputas, el dinero se libera automáticamente al vendedor.</li></ol></div>
<div class="policy-section" id="compradores"><h2>Para compradores</h2><h3>¿Cómo pago?</h3><p>Tenés 3 días hábiles para pagar tras el cierre de la subasta. Con "Comprar ahora" el pago es inmediato. Aceptamos tarjetas y métodos disponibles en Stripe.</p><h3>¿Qué pasa con mi dinero?</h3><p>El <strong>100% del monto</strong> queda retenido en custodia (escrow) vía Stripe. Se libera al vendedor <strong>72 horas después de que el tracking confirme la entrega</strong>, solo si no reportaste ningún problema.</p><h3>Período de revisión</h3><p>Tenés <strong>72 horas</strong> desde la entrega confirmada para revisar el objeto. Si no reportás nada en ese plazo, el pago se libera automáticamente.</p><h3>¿El objeto no es como se describió?</h3><p>Podés abrir una disputa desde tu panel antes de las 72 horas. Según la evidencia podemos solicitar reparación, otorgar reembolso parcial, o cancelar y reembolsarte el total.</p><div class="info-box"><strong>Tu dinero está protegido:</strong> Si abrís una disputa antes de las 72 horas, el pago queda suspendido hasta la resolución.</div><h3>Reembolsos</h3><p>Si el vendedor no envía o cancela sin razón válida, tenés derecho a reembolso completo. Puede tardar 5-10 días hábiles según tu banco.</p></div>
<div class="policy-section" id="vendedores"><h2>Para vendedores</h2><h3>¿Cuándo recibo mi pago?</h3><p>El <strong>100% del monto</strong> se libera <strong>72 horas después de que el tracking confirme la entrega</strong>, sin disputas activas, vía Stripe Connect a tu cuenta bancaria.</p><div class="info-box"><strong>Sin comisión en tu primer lote:</strong> No cobramos comisión en tu primera subasta. Las condiciones de lotes siguientes se informan antes de publicar.</div><h3>Condiciones para recibir el pago</h3><ul><li>Cuenta Stripe Connect verificada.</li><li>Tracking válido cargado en tu panel.</li><li>Sin disputas activas sobre ese lote.</li></ul><h3>¿Cuándo puede suspenderse el pago?</h3><ul><li>El comprador abre una disputa dentro de las 72 horas.</li><li>Un tercero notifica un problema con la venta.</li><li>No cumplís tus obligaciones de envío o descripción.</li><li>Tu Stripe Connect está incompleto.</li></ul><h3>Chargebacks</h3><p>Si el comprador inicia un contracargo bancario, lo detectamos automáticamente y suspendemos la custodia. Aportamos evidencia ante Stripe pero el resultado depende del banco emisor.</p><div class="warning-box"><strong>Recomendación:</strong> Enviá siempre con seguro y fotografiá el objeto antes del despacho. Es tu mejor defensa.</div></div>
<div class="policy-section" id="devoluciones"><h2>Política de devoluciones</h2><p>Las subastas en RialBids son vinculantes. Al ganar o usar "Comprar ahora", el comprador acepta los términos de la venta tal como fueron publicados.</p><h3>¿Cuándo procede una devolución?</h3><p>Solo cuando el objeto <strong>no coincide objetivamente con la descripción, fotos o materiales del listing</strong>:</p><ul><li>El objeto tiene daños no mencionados.</li><li>El objeto recibido es diferente al publicado.</li><li>Falta algún componente indicado.</li><li>La autenticidad no coincide con lo certificado.</li></ul><h3>¿Cuándo NO procede?</h3><ul><li><strong>"No me gustó" o "cambié de opinión"</strong> — no es motivo válido si el objeto fue correctamente descrito.</li><li>El comprador esperaba algo distinto pero la descripción era precisa.</li><li>Diferencias visibles en las fotos del listing.</li><li>El reporte se hizo después de las 72 horas post-entrega.</li></ul><div class="protect-box"><strong>Protección al vendedor:</strong> Si el objeto fue correctamente descrito y fotografiado, el vendedor no está obligado a aceptar devoluciones por insatisfacción personal. RialBids protege al vendedor ante reclamos sin fundamento.</div><h3>En caso de devolución válida</h3><ul><li>El comprador paga el envío de vuelta.</li><li>El objeto debe volver en el mismo estado recibido.</li><li>Si vuelve dañado por mal embalaje del comprador, el reembolso puede ser parcial o denegado.</li><li>Una vez verificado por el vendedor, RialBids procesa el reembolso.</li></ul><div class="warning-box"><strong>Importante:</strong> RialBids puede suspender cuentas de compradores con devoluciones reiteradas sin causa justificada.</div></div>
<div class="policy-section" id="disputas"><h2>Proceso de disputas</h2><p>RialBids actúa como árbitro neutral y emite resoluciones vinculantes para ambas partes.</p><h3>¿Cuándo se puede abrir?</h3><ul><li>El objeto no coincide con la descripción o fotos.</li><li>El objeto llegó dañado y el vendedor no ofrece solución.</li><li>El objeto no fue entregado en plazo razonable.</li><li>No hay tracking y el objeto no llegó.</li></ul><h3>Paso a paso</h3><ol class="steps-list"><li>El comprador reporta dentro de las 72 horas de entrega (o 14 días del pago si no llegó).</li><li>RialBids suspende la custodia y notifica al vendedor.</li><li>Ambas partes presentan evidencia: fotos, tracking, mensajes.</li><li>RialBids resuelve en hasta 5 días hábiles.</li><li>Se ejecuta: reembolso parcial, total, o pago al vendedor.</li></ol><h3>Tabla de resoluciones</h3><table class="policy-table"><thead><tr><th>Situación</th><th>Resolución habitual</th></tr></thead><tbody><tr><td>Objeto no conforme con la descripción</td><td>Reembolso parcial o total con devolución</td></tr><tr><td>Dañado en tránsito</td><td>Reclamo al seguro; reembolso si no hay seguro</td></tr><tr><td>No entregado sin tracking</td><td>Reembolso total al comprador</td></tr><tr><td>No entregado, tracking en tránsito</td><td>Investigación con transportista</td></tr><tr><td>Comprador rechaza sin motivo</td><td>Pago liberado al vendedor</td></tr><tr><td>Devolución recibida dañada</td><td>Reembolso parcial o denegado</td></tr></tbody></table><div class="info-box"><strong>Mediación obligatoria:</strong> Antes de escalar a tu banco o autoridad de consumo, pasá por nuestro proceso interno.</div></div>
<div class="policy-section" id="envios"><h2>Envíos y tracking</h2><h3>Obligaciones del vendedor</h3><ul><li>Enviar dentro de los <strong>3 días hábiles</strong> del pago confirmado.</li><li>Usar servicio con número de seguimiento válido.</li><li>Cargar el tracking en el panel antes de despachar.</li><li>Embalar adecuadamente según valor y fragilidad.</li><li>Contratar seguro para objetos de valor significativo.</li><li>Fotografiar objeto y embalaje antes del despacho.</li></ul><h3>RialBids no es responsable del envío</h3><p>No somos parte del contrato entre vendedor y transportista. Si hay daño o pérdida, el vendedor reclama directamente a la empresa de envíos.</p><h3>Costos de envío</h3><p>Deben reflejar el gasto real. No se permite inflarlos. Si el costo real fue menor al cobrado, el vendedor reembolsa la diferencia.</p></div>
<div class="policy-section" id="contacto"><h2>¿Tenés alguna pregunta?</h2><p>Contactanos ante cualquier duda sobre pagos, envíos o disputas. Respondemos en menos de 48 horas hábiles.</p><div class="contact-cta"><h3>Estamos para ayudarte</h3><p>Tanto si sos comprador como vendedor, nuestro equipo está disponible.</p><a href="mailto:soporte@rialbids.com">Contactar soporte</a></div></div>
</div>
@endsection
