@extends('layouts.app')
@section('title','Términos y condiciones — RialBids')
@section('content')
<style>
.page-wrap{max-width:800px;margin:48px auto;padding:0 24px}
.page-tag{display:inline-block;background:#f3f4f6;color:#374151;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;padding:4px 12px;border-radius:20px;margin-bottom:14px}
.page-h1{font-size:28px;font-weight:700;color:#111;margin:0 0 8px}
.page-date{font-size:13px;color:#9ca3af;display:block;margin-bottom:40px;padding-bottom:32px;border-bottom:1px solid #e5e7eb}
.page-sections{display:flex;flex-direction:column}
.page-section{display:flex;gap:20px;padding:24px 0;border-bottom:1px solid #f3f4f6}
.page-section:last-child{border-bottom:none}
.sec-num{flex-shrink:0;width:32px;height:32px;background:#f3f4f6;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;color:#374151}
.sec-h2{font-size:15px;font-weight:600;color:#111;margin:0 0 8px}
.sec-p{font-size:14px;color:#6b7280;line-height:1.75;margin:0}
.sec-link{color:#1a56db;text-decoration:none}
</style>
<div class="page-wrap">
  <div class="page-tag">Legal</div>
  <h1 class="page-h1">Términos y condiciones</h1>
  <span class="page-date">Última actualización: Mayo 2026</span>
  <div class="page-sections">
    <div class="page-section"><div class="sec-num">1</div><div><h2 class="sec-h2">Quiénes somos</h2><p class="sec-p">RialBids es una plataforma de subastas online que conecta compradores y vendedores de objetos especiales en Europa. RialBids actúa exclusivamente como intermediario: no somos propietarios de los objetos subastados ni parte del contrato de compraventa. El contrato de compraventa se establece directamente entre el comprador y el vendedor.</p></div></div>
    <div class="page-section"><div class="sec-num">2</div><div><h2 class="sec-h2">Aceptación de los términos</h2><p class="sec-p">Al acceder y usar RialBids, aceptás estos términos y condiciones en su totalidad. Si no estás de acuerdo con alguna parte, no podés usar nuestros servicios. Estos términos se rigen por la legislación española y europea aplicable.</p></div></div>
    <div class="page-section"><div class="sec-num">3</div><div><h2 class="sec-h2">Registro y cuenta</h2><p class="sec-p">Debés tener al menos 18 años para registrarte. Sos responsable de mantener la confidencialidad de tu contraseña y de todas las actividades que ocurran bajo tu cuenta. RialBids se reserva el derecho de suspender o eliminar cuentas que incumplan estos términos.</p></div></div>
    <div class="page-section"><div class="sec-num">4</div><div><h2 class="sec-h2">Pujas y compras</h2><p class="sec-p">Toda puja realizada es una oferta vinculante e irrevocable. Si ganás una subasta, estás obligado a completar la compra dentro de los 3 días siguientes al cierre. El incumplimiento del pago puede resultar en la suspensión permanente de tu cuenta y en reclamaciones por daños y perjuicios. Las subastas online están excluidas del derecho de desistimiento de 14 días previsto por la normativa europea de consumidores (artículo 16 de la Directiva 2011/83/UE).</p></div></div>
    <div class="page-section"><div class="sec-num">5</div><div><h2 class="sec-h2">Pagos y sistema de retención segura</h2><p class="sec-p">Los pagos se procesan de forma segura a través de Stripe. Una vez realizado el pago, los fondos quedan retenidos de forma segura hasta que el comprador confirme la recepción del objeto. El pago se libera automáticamente al vendedor tras la confirmación de entrega o pasados 7 días desde el marcado de envío si el comprador no reporta ningún problema.</p></div></div>
    <div class="page-section"><div class="sec-num">6</div><div><h2 class="sec-h2">Obligaciones del vendedor</h2><p class="sec-p">El vendedor se compromete a: (a) describir los objetos con exactitud y sin omisiones relevantes; (b) enviar el objeto en un plazo máximo de 10 días naturales desde la confirmación del pago, con número de seguimiento válido; (c) hacerse responsable de los daños o pérdidas durante el envío hasta la entrega; (d) cumplir con sus obligaciones fiscales correspondientes. El incumplimiento del plazo de envío puede resultar en la cancelación automática de la venta y el reembolso íntegro al comprador.</p></div></div>
    <div class="page-section"><div class="sec-num">7</div><div><h2 class="sec-h2">Protección al comprador</h2><p class="sec-p">Si el objeto recibido no corresponde a la descripción, el comprador dispone de 3 días desde la recepción para abrir una disputa a través de la plataforma. RialBids actuará como mediador. Si se confirma que el objeto no es como fue descrito, el comprador podrá recibir un reembolso total o parcial. Si el vendedor no envía el objeto en el plazo establecido, la venta se cancelará y el comprador recibirá un reembolso completo.</p></div></div>
    <div class="page-section"><div class="sec-num">8</div><div><h2 class="sec-h2">Tarifas del servicio</h2><p class="sec-p">RialBids cobra una comisión del 9% más €3 sobre el precio final de cada venta exitosa. Esta comisión se descuenta automáticamente del monto transferido al vendedor. Los gastos de envío corren por cuenta del comprador salvo indicación contraria en el lote.</p></div></div>
    <div class="page-section"><div class="sec-num">9</div><div><h2 class="sec-h2">Objetos prohibidos</h2><p class="sec-p">Está prohibido publicar: artículos ilegales, falsificaciones, objetos que infrinjan derechos de propiedad intelectual, armas, medicamentos, objetos protegidos por legislación de patrimonio cultural o especies protegidas, contenido adulto o cualquier objeto cuya venta esté restringida por la legislación aplicable. RialBids se reserva el derecho de eliminar cualquier lote sin previo aviso y sin derecho a compensación.</p></div></div>
    <div class="page-section"><div class="sec-num">10</div><div><h2 class="sec-h2">Limitación de responsabilidad</h2><p class="sec-p">RialBids no será responsable por: (a) la autenticidad, calidad o estado de los objetos subastados; (b) incumplimientos del vendedor en la entrega; (c) daños durante el envío; (d) pérdidas económicas derivadas de la participación en subastas; (e) interrupciones técnicas del servicio. La responsabilidad máxima de RialBids en cualquier caso no superará el importe de las comisiones cobradas en la transacción en cuestión.</p></div></div>
    <div class="page-section"><div class="sec-num">11</div><div><h2 class="sec-h2">Suspensión de cuentas</h2><p class="sec-p">RialBids puede suspender o cancelar cuentas de compradores que no paguen en el plazo establecido, de vendedores que no envíen los objetos o que reciban dos o más cancelaciones por incumplimiento, y de cualquier usuario que actúe de forma fraudulenta o contraria a estos términos.</p></div></div>
    <div class="page-section"><div class="sec-num">12</div><div><h2 class="sec-h2">Legislación aplicable y jurisdicción</h2><p class="sec-p">Estos términos se rigen por la legislación española. Para cualquier controversia derivada del uso de la plataforma, las partes se someten a los juzgados y tribunales españoles competentes, sin perjuicio de los derechos que la normativa europea de consumidores reconozca a los usuarios.</p></div></div>
    <div class="page-section"><div class="sec-num">13</div><div><h2 class="sec-h2">Modificaciones</h2><p class="sec-p">RialBids se reserva el derecho de modificar estos términos en cualquier momento. Los cambios serán notificados por email con al menos 15 días de antelación y publicados en esta página. El uso continuado de la plataforma tras la notificación implica la aceptación de los nuevos términos.</p></div></div>
    <div class="page-section"><div class="sec-num">14</div><div><h2 class="sec-h2">Contacto</h2><p class="sec-p">Para consultas sobre estos términos, contactanos en <a href="mailto:info@rialbids.com" class="sec-link">info@rialbids.com</a></p></div></div>
  </div>
</div>
@endsection
